version: "2"

services:
  drone-server:
    image: drone/drone:1
    ports:
      - 8000:80
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}

drone-agent:
  image: drone/drone:1
  command: agent
  restart: always
  depends_on:
    - drone-server
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - DRONE_RPC_PROTO=${DRONE_RPC_PROTO}
    - DRONE_RPC_HOST=${DRONE_RPC_HOST}
    - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
    - DRONE_RUNNER_CAPACITY=${DRONE_RUNNER_CAPACITY}
    - DRONE_RUNNER_NAME=${DRONE_RUNNER_NAME}
