kind: pipeline
type: docker
name: default

steps:
  - name: frontend
    image: golang
    commands:
      - cd frontend/pureHooks
      - docker cp -r src /myworkspace
  # - name: 构建镜像
  #   image: plugins/docker
  #   volumes:
  #     - name: docker
  #       path: /var/run/docker.sock
  #   settings:
  #     username:
  #       from_secret: ywl1641627793
  #     password:
  #       from_secret: ywl123698745
  #     repo: ywl1641627793/arthasdragon
  #     tags: "test"
