kind: pipeline
type: docker
name: default

steps:
  - name: frontend
    image: node
    commands:
      - cd frontend/pureHooks
      - yarn && yarn build
      - cp -rf * /myworkspace
  # - name: 构建镜像
  #   image: plugins/docker
  #   volumes:
  #     - name: docker
  #       path: /var/run/docker.sock
  #   settings:
  #     username:
  #       from_secret: ywl1641627793
  #     password:
  #       from_secret: ywl123698745
  #     repo: https://index.docker.io/v1/
  #     registry: ywl1641627793/arthasdragon
  #     tags: "test"
