kind: pipeline
type: docker
name: default

workspace:
  base: /frontend/pureHooks

steps:
  - name: frontend
    image: node
    commands:
      - ls
# steps:
#   - name: 构建镜像
#     image: plugins/docker
#     volumes:
#       - name: docker
#         path: /var/run/docker.sock
#     settings:
#       username:
#         from_secret: dockername
#       password:
#         from_secret: dockerpassword
#       repo: ywldragon/frontend
#       tags: "test"
