kind: pipeline

# steps:
# - name: test
#   # image: golang:1.9
#   commands:
#   - yarn install
#   - yarn start


# - name: build
#   # image: golang:1.9
#   commands:
#   - yarn install
#   - yarn start
  