kind: pipeline
name: frontend

steps:
  - name: frontend
    image: ywldragon/frontend:initial
    commands:
      - cd frontend/pureHooks
      - cd /
      - ls
      # - yarn && yarn build
      # - rm -rf /backend/java/src/main/resources/mywebsite/**
      # - cp -r /frontend/pureHooks/dist/ /backend/java/src/main/resources/mywebsite/
  # - name: backend
  #   image: ywldragon/backend:centos_java8_mysql_maven
  #   commands:
  #     - cd /backend/java
  #     - mvn clean install
  #     - mvn clean package
  # - name: 构建镜像
  #   image: plugins/docker
  #   volumes:
  #     - name: docker
  #       path: /var/run/docker.sock
  #   settings:
  #     username:
  #       from_secret: dockername
  #     password:
  #       from_secret: dockerpassword
  #     repo: ywldragon/mywebsite
  #     tags: "mywebsite build"
