kind: pipeline
type: docker
name: default

steps:
  - name: frontend
    image: node
    commands:
      - cd frontend/pureHooks
  - name: 构建镜像
    image: plugins/docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      username:
        from_secret: dockername
      password:
        from_secret: dockerpassword
      repo: ywldragon/frontend
      tags: "test"
