kind: pipeline
name: mywebsite_build

steps:
  - name: frontend
    image: ywldragon/frontend:initial
    privileged: true
    commands:
      - cd /drone/src/frontend/pureHooks
      - yarn && yarn build
      - rm -rf /drone/src/backend/java/src/main/resources/mywebsite/**
      - sudo cp -rf /drone/src/frontend/pureHooks/dist/ /drone/src/backend/java/src/main/resources/mywebsite/dist/

  - name: backend
    image: ywldragon/backend:env
    commands:
      - cd /drone/src/backend/java
      - mvn clean install
      - mvn clean package

  - name: 构建镜像
    image: plugins/docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      username:
        from_secret: dockername
      password:
        from_secret: dockerpassword
      repo: ywldragon/mywebsite
      tags:
        - latest
        - "build"

  - name: 启动镜像
    image: ywldragon/mywebsite:latest
    detach: true
