kind: pipeline
name: frontend

steps:
  - name: frontend
    image: ywldragon/frontend:initial
    commands:
      - ls
  # - name: 构建镜像
  #   image: plugins/docker
  #   volumes:
  #     - name: docker
  #       path: /var/run/docker.sock
  #   settings:
  #     username:
  #       from_secret: dockername
  #     password:
  #       from_secret: dockerpassword
  #     repo: ywldragon/frontend
  #     tags: "test"
