apiVersion: v1
kind: Pod
metadata:
  name: drone
spec:
  containers:
    - name: runner
      image: drone/drone-runner-kube:latest
      ports:
        - containerPort: 3000
      env:
        - name: DRONE_RPC_HOST
          value: 49.235.112.89:8000
        - name: DRONE_RPC_PROTO
          value: http
        - name: DRONE_RPC_SECRET
          value: DRAGON_123456
